import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  Container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    padding: 10,
  },
  Button: {
    backgroundColor: "#90cc0c",
    width: "90%",
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 7,
    color: "white",
  },
  Text: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    fontWeight: "200",
    marginBottom: 30,
    color: "#3b3b3b",
    alignSelf: "center",
  },
  TextButton: {
    color: "#fff",
    fontSize: 18,
  },
  Title: {
    textAlign: "center",
    color: "black",
    fontSize: 30,
    fontWeight: "700",
    marginBottom: 5,
  },
  TextInput: {
    backgroundColor: "#f9f9f9",
    width: "90%",
    marginBottom: 15,
    color: "#222",
    fontSize: 16,
    borderRadius: 7,
    padding: 15,
    height: 55,
  },
  Back: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    alignSelf: "stretch",
    marginLeft: 30,
  },
  TextInputError: {
    backgroundColor: "#f9f9f9",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#f02849",
    width: "90%",
    marginBottom: 15,
    color: "#222",
    fontSize: 16,
    borderRadius: 7,
    padding: 15,
    height: 55,
  },
  Icon: {
    position: "absolute",
    padding: 15,
    alignSelf: "flex-end",
  },
  SectionInput: {
    width: "100%",
    alignItems: "center",
  },
});