name: Expo Publish with Cache
on:
  pull_request:
    branches:
      - main
jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: print secrets
        run: |
          echo $PWD
          echo $DEV_ENV_FILE >> /Users/runner/work/nutrieasy-frontend/nutrieasy-frontend/google-services.json
          cat /Users/runner/work/nutrieasy-frontend/nutrieasy-frontend/google-services.json
        shell: bash
        env:
          DEV_ENV_FILE : ${{ secrets.SECRET1 }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEV_ENV_FILE
          path: /Users/runner/work/nutrieasy-frontend/nutrieasy-frontend/google-services.json
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_CLI_TOKEN }}
      - name: Install deps
        run: yarn install
      - name: Build Android APK Bundle
        run: expo build:android
        








